Milestone2
AlanSoto31/ror-social-scaffold pull request #3
Opened 2021-01-15 21:03 UTC by janis-jenny

-  Add send invitation request.

- Add button “Add friend” next to the name of user who is not my friend yet - on both users’ list and single user page.

- Add pending friendship invitations sent to me from other users.

- Add accept or reject friendships invitation buttons

- Number of comments and likes in the timeline

2021-01-16 03:11 UTC, mcrd25 requested changes
# Changes Required :mag: 

Hi Team! :wave: 

Thanks so much for submitting this milestone for the review!
It's a good start, but let's address some required changes below to make it even better :slightly_smiling_face: 


#### Required Changes
- You missing tests! See [this screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)
- You should only see someone else's post after you've friended them. Currently, I can see their posts on my timeline before I friend them. see [this screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from Pathwright project description
- See additional Required Comments below

Hope my review was helpful. :slightly_smiling_face: 

***Please makes changes and submit another review request.
If you have any questions, let me know here or email (preferably) or on slack, and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

If you liked my review, consider upskilling me on LinkedIn. And please do connect. [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2021-01-16 03:11 UTC, mcrd25 commented on app/models/user.rb
> +  has_many :pending_friendships, -> { where(status: false) }, class_name: 'Friendship'
This is a good start for the next milestone but before this, you should look into adding an inverted friendship relationship. See this link on how it works and improves the performance of your application: https://smartfunnycool.com/friendships-in-activerecord/

2021-01-19 17:01 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] I can see my friends' posts, but I can't see my own, please update it so I can see both my and friends posts ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-19 18:00 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-19 18:00 UTC, Spayco commented on app/controllers/posts_controller.rb
> +    @timeline_posts ||= Post.all.ordered_by_most_recent.where(user_id: current_user.friends).or(Post.all.ordered_by_most_recent.where(user_id: current_user.id))
- [ ]  you can use a better approach 
```Ruby
Post.where(user: (self.friends.to_a << self))
# this would be in the User model.
```

2021-01-19 19:34 UTC, merged